# Generated by Django 3.2.3 on 2021-05-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('summoner_name', models.TextField()),
                ('summoner_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RankDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Cumulative_LP', models.IntegerField()),
                ('league_points', models.IntegerField()),
                ('Summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemotrack_app.summoner')),
            ],
        ),
    ]
