# Generated by Django 3.2.3 on 2021-05-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teemotrack_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankdatapoint',
            old_name='Cumulative_LP',
            new_name='cumulative_lp',
        ),
        migrations.RenameField(
            model_name='rankdatapoint',
            old_name='Summoner',
            new_name='summoner',
        ),
        migrations.RenameField(
            model_name='rankdatapoint',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
