# Generated by Django 3.2.3 on 2021-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teemotrack_app', '0002_auto_20210520_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankdatapoint',
            name='division',
            field=models.CharField(default='I', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankdatapoint',
            name='tier',
            field=models.TextField(default='UNRANKED'),
            preserve_default=False,
        ),
    ]
