# Generated by Django 3.2.3 on 2021-06-16 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teemotrack_app', '0003_auto_20210520_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='last_queried',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
